'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es' | 'it' | 'fr' | 'de' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'hero.title': 'Discord Designer & Community Manager.',
    'hero.subtitle': 'Proven expertise in designing and scaling high-performance server infrastructure. Advanced permissions and custom bot development.',
    'section.projects': 'Selected Projects',
    'nav.home': 'Home',
    'nav.showcase': 'Showcase',
    'section.experience': 'Work Experience',
    'cta.title': "Let's work together.",
    'cta.subtitle': "I'm currently available for freelance work. If you have a project that you want to get started, think you need my help with something or just fancy saying hey, then get in touch.",
    'cta.button': 'Email me',
    'discord.listening': 'Listening to',
    'discord.playing': 'Playing',
    'discord.activity': 'Activity',
    'discord.chilling': 'Currently chilling...',
    'discord.message': 'Send Discord Message',
    'footer.copy': 'Nynele.',
    'time.local': 'LOCAL TIME',
    'audio.play': 'Play',
    'audio.pause': 'Pause',
    'job.present': 'Present',
    'experience.active': 'Active Positions',
    'experience.past': 'Past Positions',
    '404.title': 'Page not found',
    '404.subtitle': "The page you are looking for doesn't exist or has been moved. Don't worry, even the best designers get lost sometimes.",
    '404.button': 'Back to Home',
    'pitch.hero.title': 'Discord Designer & Community Manager.',
    'pitch.hero.subtitle': 'Proven expertise in designing and scaling high-performance server infrastructure. Advanced permissions and custom bot development.',
    'pitch.why.title': 'Why hire me?',
    'pitch.why.1': 'Expert Configuration',
    'pitch.why.1.desc': 'Advanced permissions and hierarchy setup.',
    'pitch.why.2': 'Custom Automation',
    'pitch.why.2.desc': 'Tailored bot solutions for your specific needs.',
    'pitch.why.3': 'Community Growth',
    'pitch.why.3.desc': 'Proven strategies to increase engagement and retention.',
    'pitch.cta': 'Ready to scale?',
    'pitch.results.title': 'The Results',
    'pitch.results.subtitle': "I don't just build servers; I build ecosystems. Here is what my architecture looks like under the hood.",
    'pitch.final.title': "Let's build something great.",
    'pitch.final.subtitle': 'Available for new partnerships and consultations.',
    'pitch.final.button': 'Get Started via Discord',
    'pitch.example.bot.name': 'Community Hub',
    'pitch.example.bot.msg': 'Poll created by Nynele 🤫',
    'pitch.example.bot.embed.title': 'Question',
    'pitch.example.bot.embed.desc': 'Do you like this new dashboard? 💕',
    'pitch.example.bot.embed.field1': 'Choices',
    'pitch.example.bot.embed.field1.val': 'A: Yes | B: Definitely | C: Absolutely!!!',
    'pitch.example.bot.embed.field2': 'Ends',
    'pitch.example.bot.embed.field2.val': 'In 1 day',
    'pitch.stats.servers': 'Servers Optimized',
    'pitch.stats.members': 'Members Managed',
    'pitch.stats.experience': 'Years Experience',
    'pitch.commands.title': 'Interactive Commands',
    'pitch.commands.hire.desc': 'Open a ticket to discuss your project.',
    'pitch.commands.info.desc': 'View my services and pricing.',
    'pitch.commands.portfolio.desc': 'Browse my latest Discord setups.',
    'pitch.feature.mod.title': 'Advanced Moderation',
    'pitch.feature.mod.desc': 'Keep your community safe with multi-user bans, kicks, and advanced logging. Automate protection against raids and spam without breaking a sweat.',
    'pitch.feature.notifications.title': 'Real-time Notifications',
    'pitch.feature.notifications.desc': 'Keep your users informed with automated YouTube, Twitch, and Social Media alerts directly in your channels.',
    'pitch.feature.embeds.title': 'Beautiful Embeds',
    'pitch.feature.embeds.desc': 'Professional documentation and rule sets designed with high-impact visuals and intuitive structure.',
    'pitch.feature.custom.title': 'Total Customization',
    'pitch.feature.custom.desc': 'Every bot I design is unique. From branding to specific logic, I build features that fit your community like a glove.',
    // Sledge Example
    'pitch.example.mod.title': '[ALERT] Anti-Scam Detection',
    'pitch.example.mod.desc': 'A suspicious message was detected and removed.',
    'pitch.example.mod.field.overview': 'Moderation Overview',
    'pitch.example.mod.field.user': 'User',
    'pitch.example.mod.field.channel': 'Channel',
    'pitch.example.mod.field.incident': 'Incident',
    'pitch.example.mod.btn.ban': 'Ban',
    'pitch.example.mod.btn.history': 'History',
    'pitch.example.mod.btn.dismiss': 'Dismiss',
    'pitch.example.mod.btn.evidence': 'Evidence',
    // MeliasBot Example
    'pitch.example.notif.msg': '📹 Melias just started a live stream on Twitch!\nhttps://twitch.tv/meliasoficial\n@Mention - Directos',
    'pitch.example.notif.embed.title': 'Twitch',
    'pitch.example.notif.embed.desc': 'meliasoficial - Twitch',
    // Normativas Example
    'pitch.example.rules.desc': '🔨 **Compliance with the rules is mandatory.**\n\nThis server is governed by the **Terms of Service** and **Community Guidelines** of Discord.\n\n`The rules are mandatory to ensure a peaceful and respectful stay. Ignorance of them does not exempt you from them.`',
    'pitch.example.rules.f1': '🔴 Behavior',
    'pitch.example.rules.f1.v': 'Treat users with respect. Discrimination or harassment is not allowed.',
    'pitch.example.rules.f2': '🔴 Chat usage',
    'pitch.example.rules.f2.v': 'Avoid repetitive messages, chains or promotions.',
    'pitch.example.rules.f3': '🔴 Appropriate content',
    'pitch.example.rules.f3.v': 'NSFW or similar content is not allowed.',
    'pitch.example.rules.f4': '🔴 Channel usage',
    'pitch.example.rules.f4.v': 'Use each channel for what it was created for.',
    'pitch.example.rules.f5': '🔴 Privacy',
    'pitch.example.rules.f5.v': 'Do not share personal information of any kind.',
    'pitch.example.rules.f6': '🔴 Moderation',
    'pitch.example.rules.f6.v': 'Do not question the decisions of the staff.',
    'pitch.example.rules.footer': 'In case of doubts, visit the server info, or contact the staff.',
    'pitch.example.rules.btn1': 'Review rules',
    'pitch.example.rules.btn2': 'View info',
    // Customization Examples
    'pitch.example.custom.bio1': 'The most complete bot for Melias community. Developed by Nynele Studio.',
    'pitch.example.custom.bio2': 'Advanced security and tactical moderation for professional servers.',
    'pitch.example.custom.status': '🛡️ Protecting your server',
    // Audio Player Widget
    'audio.select_track': 'Select Track',
    'audio.playing_lofi': 'Playing Lo-Fi',
    'audio.lofi_background': 'Lo-Fi Background',
    'audio.live_sync_menu': 'Live Sync Menu',
    'audio.force_refresh': 'Force Refresh Sync',
    'audio.force_refresh_desc': 'Re-fetch active Discord presence',
    'audio.reset_search': 'Reset Video Search',
    'audio.reset_search_desc': 'Reset to first search result',
    // Discord Profile / Message
    'discord.about_me': 'About Me',
    // Bot Builder
    'builder.default.name': 'My Custom Bot',
    'builder.default.bio': 'I am a professional Discord bot tailored to your community needs.',
    'builder.default.tag1': 'Custom',
    'builder.default.tag2': 'Security',
    'builder.default.tag3': 'Fast',
    'builder.app_icon': 'App Icon',
    'builder.remove': 'Remove',
    'builder.name': 'Name',
    'builder.description_label': 'Description (Maximum 400 characters)',
    'builder.description_help': "Your description will appear in the About Me section of your bot's profile.",
    'builder.tags_label': 'Tags (Maximum 5)',
    'builder.tags_placeholder': 'Add up to 5 tags...',
    'builder.preview_title': 'Live Profile Preview',
    'builder.preview_help': 'This is how your custom brand will look in Discord.',
    'builder.custom_status': '🛡️ Custom Bot System',
    // Showcase
    'pitch.trusted_by': 'TRUSTED BY',
  },
  es: {
    'hero.title': 'Diseñador de Discord y Community Manager.',
    'hero.subtitle': 'Experiencia demostrada en el diseño y escalado de infraestructura de servidores de alto rendimiento. Permisos avanzados y desarrollo de bots personalizados.',
    'section.projects': 'Proyectos Seleccionados',
    'nav.home': 'Inicio',
    'nav.showcase': 'Showcase',
    'section.experience': 'Experiencia Laboral',
    'cta.title': 'Trabajemos juntos.',
    'cta.subtitle': 'Actualmente estoy disponible para trabajos freelance. Si tienes un proyecto que quieras empezar, crees que necesitas mi ayuda o simplemente quieres saludar, ponte en contacto.',
    'cta.button': 'Enviame un email',
    'discord.listening': 'Escuchando',
    'discord.playing': 'Jugando a',
    'discord.activity': 'Actividad',
    'discord.chilling': 'Relajándose...',
    'discord.message': 'Enviar mensaje por Discord',
    'footer.copy': 'Nynele.',
    'time.local': 'HORA LOCAL',
    'audio.play': 'Reproducir',
    'audio.pause': 'Pausar',
    'job.present': 'Presente',
    'experience.active': 'Puestos Activos',
    'experience.past': 'Historial Laboral',
    '404.title': 'Página no encontrada',
    '404.subtitle': 'La página que buscas no existe o ha sido movida. No te preocupes, hasta los mejores diseñadores se pierden a veces.',
    '404.button': 'Volver al Inicio',
    'pitch.hero.title': 'Diseñador de Discord y Community Manager.',
    'pitch.hero.subtitle': 'Experiencia demostrada en el diseño y escalado de infraestructura de servidores de alto rendimiento. Permisos avanzados y desarrollo de bots personalizados.',
    'pitch.why.title': '¿Por qué contratarme?',
    'pitch.why.1': 'Configuración Experta',
    'pitch.why.1.desc': 'Configuración avanzada de permisos y jerarquías.',
    'pitch.why.2': 'Automatización a Medida',
    'pitch.why.2.desc': 'Soluciones de bots personalizadas para tus necesidades.',
    'pitch.why.3': 'Crecimiento de Comunidad',
    'pitch.why.3.desc': 'Estrategias probadas para aumentar la participación y retención.',
    'pitch.cta': '¿Listo para escalar?',
    'pitch.results.title': 'Los Resultados',
    'pitch.results.subtitle': 'No solo construyo servidores; construyo ecosistemas. Así es como se ve mi arquitectura por dentro.',
    'pitch.final.title': 'Construyamos algo grande.',
    'pitch.final.subtitle': 'Disponible para nuevas colaboraciones y consultorías.',
    'pitch.final.button': 'Empezar vía Discord',
    'pitch.example.bot.name': 'Centro de Comunidad',
    'pitch.example.bot.msg': 'Encuesta creada por Nynele 🤫',
    'pitch.example.bot.embed.title': 'Pregunta',
    'pitch.example.bot.embed.desc': '¿Te gusta este nuevo panel? 💕',
    'pitch.example.bot.embed.field1': 'Opciones',
    'pitch.example.bot.embed.field1.val': 'A: Sí | B: Definitivamente | C: ¡Absolutamente!',
    'pitch.example.bot.embed.field2': 'Termina',
    'pitch.example.bot.embed.field2.val': 'En 1 día',
    'pitch.stats.servers': 'Servidores Optimizados',
    'pitch.stats.members': 'Miembros Gestionados',
    'pitch.stats.experience': 'Años de Experiencia',
    'pitch.commands.title': 'Comandos Interactivos',
    'pitch.commands.hire.desc': 'Abre un ticket para hablar de tu proyecto.',
    'pitch.commands.info.desc': 'Ver mis servicios y precios.',
    'pitch.commands.portfolio.desc': 'Explora mis últimos trabajos en Discord.',
    'pitch.feature.mod.title': 'Moderación Avanzada',
    'pitch.feature.mod.desc': 'Mantén tu comunidad segura con baneos múltiples, expulsiones y registros avanzados. Automatiza la protección contra raids y spam sin esfuerzo.',
    'pitch.feature.notifications.title': 'Notificaciones en Tiempo Real',
    'pitch.feature.notifications.desc': 'Mantén a tus usuarios informados con alertas automáticas de YouTube, Twitch y Redes Sociales directamente en tus canales.',
    'pitch.feature.embeds.title': 'Embeds Preciosos',
    'pitch.feature.embeds.desc': 'Documentación profesional y normativas diseñadas con visuales de alto impacto y estructura intuitiva.',
    'pitch.feature.custom.title': 'Personalización Total',
    'pitch.feature.custom.desc': 'Cada bot que diseño es único. Desde la marca hasta la lógica específica, construyo funcionalidades que se adaptan a tu comunidad como un guante.',
    // Sledge Example
    'pitch.example.mod.title': '[ALERTA] Detección de Anti-Scam',
    'pitch.example.mod.desc': 'Se ha detectado y eliminado un mensaje sospechoso.',
    'pitch.example.mod.field.overview': 'Resumen de Moderación',
    'pitch.example.mod.field.user': 'Usuario',
    'pitch.example.mod.field.channel': 'Canal',
    'pitch.example.mod.field.incident': 'Incidente',
    'pitch.example.mod.btn.ban': 'Banear',
    'pitch.example.mod.btn.history': 'Historial',
    'pitch.example.mod.btn.dismiss': 'Descartar',
    'pitch.example.mod.btn.evidence': 'Evidencia',
    'pitch.example.notif.msg': '📹 ¡Melias acaba de empezar directo en Twitch!\nhttps://twitch.tv/meliasoficial\n@Mención - Directos',
    'pitch.example.notif.embed.title': 'Twitch',
    'pitch.example.notif.embed.desc': 'meliasoficial - Twitch',
    // Normativas Example
    'pitch.example.rules.desc': '🔨 **El cumplimiento de la normativa es obligatorio.**\n\nEste servidor se rige con los **Terminos de Servicio** y **Directrices de la Comunidad** de Discord.\n\n\`Las normas son de cumplimiento obligatorio para asegurar una estancia pacifica y respetuosa. El desconocimiento de ellas no te exime de las mismas.\`',
    'pitch.example.rules.f1': '🔴 Comportamiento',
    'pitch.example.rules.f1.v': 'Trata a los usuarios con respeto. No se permite la discriminación ni acoso.',
    'pitch.example.rules.f2': '🔴 Uso de chats',
    'pitch.example.rules.f2.v': 'Evita mensajes repetitivos, cadenas o promociones.',
    'pitch.example.rules.f3': '🔴 Contenido apropiado',
    'pitch.example.rules.f3.v': 'No está permitido el contenido NSFW o similares.',
    'pitch.example.rules.f4': '🔴 Uso de canales',
    'pitch.example.rules.f4.v': 'Utiliza cada canal para lo que fue creado.',
    'pitch.example.rules.f5': '🔴 Privacidad',
    'pitch.example.rules.f5.v': 'No compartas información personal de ningún tipo.',
    'pitch.example.rules.f6': '🔴 Moderación',
    'pitch.example.rules.f6.v': 'No pongas en duda las decisiones del personal.',
    'pitch.example.rules.footer': 'En caso de dudas, visita la info del servidor, o contacta con el personal.',
    'pitch.example.rules.btn1': 'Revisar la normativa',
    'pitch.example.rules.btn2': 'Ver información',
    // Customization Examples
    'pitch.example.custom.bio1': 'El bot más completo para la comunidad de Melias. Desarrollado por Nynele Studio.',
    'pitch.example.custom.bio2': 'Seguridad avanzada y moderación táctica para servidores profesionales.',
    'pitch.example.custom.status': '🛡️ Protegiendo tu servidor',
    // Audio Player Widget
    'audio.select_track': 'Seleccionar Pista',
    'audio.playing_lofi': 'Reproduciendo Lo-Fi',
    'audio.lofi_background': 'Lo-Fi de Fondo',
    'audio.live_sync_menu': 'Menú de Sincronización en Vivo',
    'audio.force_refresh': 'Forzar Sincronización',
    'audio.force_refresh_desc': 'Volver a obtener la actividad de Discord',
    'audio.reset_search': 'Restablecer Búsqueda',
    'audio.reset_search_desc': 'Volver al primer resultado de video',
    // Discord Profile / Message
    'discord.about_me': 'Sobre Mí',
    // Bot Builder
    'builder.default.name': 'Mi Bot Personalizado',
    'builder.default.bio': 'Soy un bot de Discord profesional adaptado a las necesidades de tu comunidad.',
    'builder.default.tag1': 'Personalizado',
    'builder.default.tag2': 'Seguridad',
    'builder.default.tag3': 'Rápido',
    'builder.app_icon': 'Icono de la App',
    'builder.remove': 'Eliminar',
    'builder.name': 'Nombre',
    'builder.description_label': 'Descripción (Máximo 400 caracteres)',
    'builder.description_help': 'Tu descripción aparecerá en la sección Sobre Mí del perfil de tu bot.',
    'builder.tags_label': 'Etiquetas (Máximo 5)',
    'builder.tags_placeholder': 'Añade hasta 5 etiquetas...',
    'builder.preview_title': 'Vista Previa de Perfil en Vivo',
    'builder.preview_help': 'Así es como se verá tu marca personalizada en Discord.',
    'builder.custom_status': '🛡️ Sistema de Bot Personalizado',
    // Showcase
    'pitch.trusted_by': 'CON LA CONFIANZA DE',
  },
  it: {
    'hero.title': 'Designer di Discord & Community Manager.',
    'hero.subtitle': 'Comprovata esperienza nella progettazione e nel ridimensionamento di infrastrutture server ad alte prestazioni. Permessi avanzati e sviluppo di bot personalizzati.',
    'section.projects': 'Progetti Selezionati',
    'nav.home': 'Home',
    'nav.showcase': 'Showcase',
    'section.experience': 'Esperienze Lavorative',
    'cta.title': 'Lavoriamo insieme.',
    'cta.subtitle': 'Attualmente sono disponibile per lavori freelance. Se hai un progetto che vuoi avviare, pensi di aver bisogno del mio aiuto o vuoi semplicemente fare un saluto, mettiti in contatto.',
    'cta.button': 'Scrivimi via email',
    'discord.listening': 'In ascolto di',
    'discord.playing': 'In gioco a',
    'discord.activity': 'Attività',
    'discord.chilling': 'Al momento mi sto rilassando...',
    'discord.message': 'Invia messaggio su Discord',
    'footer.copy': 'Nynele.',
    'time.local': 'ORA LOCALE',
    'audio.play': 'Riproduci',
    'audio.pause': 'Pausa',
    'job.present': 'Presente',
    'experience.active': 'Posizioni Attive',
    'experience.past': 'Posizioni Passate',
    '404.title': 'Pagina non trovata',
    '404.subtitle': 'La pagina che stai cercando non esiste o è stata spostata. Non preoccuparti, anche i migliori designer si perdono a volte.',
    '404.button': 'Torna alla Home',
    'pitch.hero.title': 'Designer di Discord & Community Manager.',
    'pitch.hero.subtitle': 'Comprovata esperienza nella progettazione e nel ridimensionamento di infrastrutture server ad alte prestazioni. Permessi avanzati e sviluppo di bot personalizzati.',
    'pitch.why.title': 'Perché assumermi?',
    'pitch.why.1': 'Configurazione Esperta',
    'pitch.why.1.desc': 'Configurazione avanzata dei permessi e della gerarchia.',
    'pitch.why.2': 'Automazione su Misura',
    'pitch.why.2.desc': 'Soluzioni bot personalizzate per le tue esigenze specifiche.',
    'pitch.why.3': 'Crescita della Community',
    'pitch.why.3.desc': 'Strategie collaudate per aumentare il coinvolgimento e la fidelizzazione.',
    'pitch.cta': 'Pronto a crescere?',
    'pitch.results.title': 'I Risultati',
    'pitch.results.subtitle': 'Non costruisco solo server; costruisco ecosistemi. Ecco come appare la mia architettura sotto il cofano.',
    'pitch.final.title': 'Costruiamo qualcosa di grande.',
    'pitch.final.subtitle': 'Disponibile per nuove partnership e consulenze.',
    'pitch.final.button': 'Inizia su Discord',
    'pitch.example.bot.name': 'Centro della Community',
    'pitch.example.bot.msg': 'Sondaggio creato da Nynele 🤫',
    'pitch.example.bot.embed.title': 'Domanda',
    'pitch.example.bot.embed.desc': 'Ti piace questo nuovo pannello di controllo? 💕',
    'pitch.example.bot.embed.field1': 'Opzioni',
    'pitch.example.bot.embed.field1.val': 'A: Sì | B: Decisamente | C: Assolutamente!!!',
    'pitch.example.bot.embed.field2': 'Termina',
    'pitch.example.bot.embed.field2.val': 'Tra 1 giorno',
    'pitch.stats.servers': 'Server Ottimizzati',
    'pitch.stats.members': 'Membri Gestiti',
    'pitch.stats.experience': 'Anni di Esperienza',
    'pitch.commands.title': 'Comandi Interattivi',
    'pitch.commands.hire.desc': 'Apri un ticket per discutere del tuo progetto.',
    'pitch.commands.info.desc': 'Visualizza i miei servizi e prezzi.',
    'pitch.commands.portfolio.desc': 'Esplora i miei ultimi lavori su Discord.',
    'pitch.feature.mod.title': 'Moderazione Avanzata',
    'pitch.feature.mod.desc': 'Mantieni la tua community al sicuro con ban multipli, espulsioni e log avanzati. Automatizza la protezione contro raid e spam senza fatica.',
    'pitch.feature.notifications.title': 'Notifiche in Tempo Reale',
    'pitch.feature.notifications.desc': 'Mantieni informati i tuoi utenti con avvisi automatici di YouTube, Twitch e Social Media direttamente nei tuoi canali.',
    'pitch.feature.embeds.title': 'Embed Bellissimi',
    'pitch.feature.embeds.desc': 'Documentazione professionale e regolamenti progettati con elementi visivi ad alto impatto e struttura intuitiva.',
    'pitch.feature.custom.title': 'Personalizzazione Totale',
    'pitch.feature.custom.desc': 'Ogni bot che progetto è unico. Dal branding alla logica specifica, creo funzionalità che si adattano alla tua community come un guanto.',
    // Sledge Example
    'pitch.example.mod.title': '[ALLERTA] Rilevamento Anti-Scam',
    'pitch.example.mod.desc': 'Rilevato e rimosso un messaggio sospetto.',
    'pitch.example.mod.field.overview': 'Panoramica di Moderazione',
    'pitch.example.mod.field.user': 'Utente',
    'pitch.example.mod.field.channel': 'Canale',
    'pitch.example.mod.field.incident': 'Incidente',
    'pitch.example.mod.btn.ban': 'Banna',
    'pitch.example.mod.btn.history': 'Cronologia',
    'pitch.example.mod.btn.dismiss': 'Ignora',
    'pitch.example.mod.btn.evidence': 'Prove',
    'pitch.example.notif.msg': '📹 Melias ha appena iniziato una trasmissione in diretta su Twitch!\nhttps://twitch.tv/meliasoficial\n@Mention - Dirette',
    'pitch.example.notif.embed.title': 'Twitch',
    'pitch.example.notif.embed.desc': 'meliasoficial - Twitch',
    // Normativas Example
    'pitch.example.rules.desc': '🔨 **Il rispetto delle regole è obbligatorio.**\n\nQuesto server è disciplinato dai **Termini di servizio** e dalle **Linee guida della community** di Discord.\n\n`Le regole sono obbligatorie per garantire una permanenza pacifica e rispettosa. L\'ignoranza di esse non esime dal rispettarle.`',
    'pitch.example.rules.f1': '🔴 Comportamento',
    'pitch.example.rules.f1.v': 'Tratta gli utenti con rispetto. Non sono ammesse discriminazioni o molestie.',
    'pitch.example.rules.f2': '🔴 Uso della chat',
    'pitch.example.rules.f2.v': 'Evita messaggi ripetitivi, catene o promozioni.',
    'pitch.example.rules.f3': '🔴 Contenuto appropriato',
    'pitch.example.rules.f3.v': 'Non sono ammessi contenuti NSFW o simili.',
    'pitch.example.rules.f4': '🔴 Uso dei canali',
    'pitch.example.rules.f4.v': 'Utilizza ogni canale per lo scopo per cui è stato creato.',
    'pitch.example.rules.f5': '🔴 Privacy',
    'pitch.example.rules.f5.v': 'Non condividere informazioni personali di alcun tipo.',
    'pitch.example.rules.f6': '🔴 Moderazione',
    'pitch.example.rules.f6.v': 'Non mettere in discussione le decisioni dello staff.',
    'pitch.example.rules.footer': 'In caso di dubbi, visita le info del server o contatta lo staff.',
    'pitch.example.rules.btn1': 'Leggi le regole',
    'pitch.example.rules.btn2': 'Vedi info',
    // Customization Examples
    'pitch.example.custom.bio1': 'Il bot più completo per la community di Melias. Sviluppato da Nynele Studio.',
    'pitch.example.custom.bio2': 'Sicurezza avanzata e moderación táctica per server professionali.',
    'pitch.example.custom.status': '🛡️ Proteggo il tuo server',
    // Audio Player Widget
    'audio.select_track': 'Seleziona Traccia',
    'audio.playing_lofi': 'Riproduzione Lo-Fi',
    'audio.lofi_background': 'Lo-Fi di Sottofondo',
    'audio.live_sync_menu': 'Menu di Sincronizzazione Live',
    'audio.force_refresh': 'Forza Aggiornamento Sincronizzazione',
    'audio.force_refresh_desc': 'Recupera di nuovo la presenza attiva di Discord',
    'audio.reset_search': 'Ripristina Ricerca Video',
    'audio.reset_search_desc': 'Ripristina al primo risultato di ricerca',
    // Discord Profile / Message
    'discord.about_me': 'Su di Me',
    // Bot Builder
    'builder.default.name': 'Mio Bot Personalizzato',
    'builder.default.bio': 'Sono un bot di Discord professionale personalizzato in base alle esigenze della tua community.',
    'builder.default.tag1': 'Personalizzato',
    'builder.default.tag2': 'Sicurezza',
    'builder.default.tag3': 'Veloce',
    'builder.app_icon': 'Icona dell\'App',
    'builder.remove': 'Rimuovi',
    'builder.name': 'Nome',
    'builder.description_label': 'Descrizione (Massimo 400 caratteri)',
    'builder.description_help': "La tua descrizione apparirà nella sezione Su di Me del profilo del tuo bot.",
    'builder.tags_label': 'Tag (Massimo 5)',
    'builder.tags_placeholder': 'Aggiungi fino a 5 tag...',
    'builder.preview_title': 'Anteprima Profilo in Tempo Reale',
    'builder.preview_help': 'Ecco come apparirà il tuo marchio personalizzato su Discord.',
    'builder.custom_status': '🛡️ Sistema Bot Personalizzato',
    // Showcase
    'pitch.trusted_by': 'CON LA FIDUCIA DI',
  },
  fr: {
    'hero.title': 'Designer Discord & Community Manager.',
    'hero.subtitle': 'Expertise reconnue dans la conception et l\'évolution d\'infrastructures de serveurs haute performance. Permissions avancées et développement de bots personnalisés.',
    'section.projects': 'Projets Sélectionnés',
    'nav.home': 'Accueil',
    'nav.showcase': 'Showcase',
    'section.experience': 'Expérience Professionnelle',
    'cta.title': 'Travaillons ensemble.',
    'cta.subtitle': 'Je suis actuellement disponible pour des missions en freelance. Si vous avez un projet que vous souhaitez lancer, si vous pensez avoir besoin de mon aide ou si vous voulez simplement dire bonjour, contactez-moi.',
    'cta.button': 'Envoyez-moi un email',
    'discord.listening': 'Écoute',
    'discord.playing': 'Joue à',
    'discord.activity': 'Activité',
    'discord.chilling': 'Actuellement en train de me détendre...',
    'discord.message': 'Envoyer un message Discord',
    'footer.copy': 'Nynele.',
    'time.local': 'HEURE LOCALE',
    'audio.play': 'Lire',
    'audio.pause': 'Pause',
    'job.present': 'Présent',
    'experience.active': 'Postes Actifs',
    'experience.past': 'Postes Précédents',
    '404.title': 'Page non trouvée',
    '404.subtitle': 'La page que vous recherchez n\'existe pas ou a été déplacée. Ne vous inquiétez pas, même les meilleurs designers se perdent parfois.',
    '404.button': 'Retour à l\'accueil',
    'pitch.hero.title': 'Designer Discord & Community Manager.',
    'pitch.hero.subtitle': 'Expertise reconnue dans la conception et l\'évolution d\'infrastructures de serveurs haute performance. Permissions avancées et développement de bots personnalisés.',
    'pitch.why.title': 'Pourquoi m\'embaucher ?',
    'pitch.why.1': 'Configuration Experte',
    'pitch.why.1.desc': 'Configuration avancée des permissions et des hiérarchies.',
    'pitch.why.2': 'Automatisation sur Mesure',
    'pitch.why.2.desc': 'Solutions de bots adaptées à vos besoins spécifiques.',
    'pitch.why.3': 'Croissance de la Communauté',
    'pitch.why.3.desc': 'Stratégies éprouvées pour augmenter l\'engagement et la rétention.',
    'pitch.cta': 'Prêt à évoluer ?',
    'pitch.results.title': 'Les Résultats',
    'pitch.results.subtitle': 'Je ne construis pas seulement des serveurs, je crée des écosystèmes. Voici à quoi ressemble mon architecture sous le capot.',
    'pitch.final.title': 'Créons quelque chose de grand.',
    'pitch.final.subtitle': 'Disponible pour de nouveaux partenariats et consultations.',
    'pitch.final.button': 'Commencer via Discord',
    'pitch.example.bot.name': 'Centre de la Communauté',
    'pitch.example.bot.msg': 'Sondaggio creato da Nynele 🤫',
    'pitch.example.bot.embed.title': 'Domanda',
    'pitch.example.bot.embed.desc': 'Aimez-vous ce nouveau tableau de bord ? 💕',
    'pitch.example.bot.embed.field1': 'Choix',
    'pitch.example.bot.embed.field1.val': 'A: Oui | B: Définitivement | C: Absolument !!!',
    'pitch.example.bot.embed.field2': 'Prend fin',
    'pitch.example.bot.embed.field2.val': 'Dans 1 jour',
    'pitch.stats.servers': 'Serveurs Optimisés',
    'pitch.stats.members': 'Membres Gérés',
    'pitch.stats.experience': 'Années d\'Expérience',
    'pitch.commands.title': 'Commandes Interactives',
    'pitch.commands.hire.desc': 'Ouvrez un ticket pour discuter de votre projet.',
    'pitch.commands.info.desc': 'Voir mes services et tarifs.',
    'pitch.commands.portfolio.desc': 'Parcourez mes dernières configurations Discord.',
    'pitch.feature.mod.title': 'Modération Avancée',
    'pitch.feature.mod.desc': 'Sécurisez votre communauté avec des exclusions, bannissements d\'utilisateurs multiples et journaux d\'événements avancés. Automatisez sans effort la protection contre les raids et le spam.',
    'pitch.feature.notifications.title': 'Notifications en Temps Réel',
    'pitch.feature.notifications.desc': 'Informez vos utilisateurs avec des alertes automatiques YouTube, Twitch et Réseaux Sociaux directement dans vos salons.',
    'pitch.feature.embeds.title': 'Superbes Embeds',
    'pitch.feature.embeds.desc': 'Documentation professionnelle et règlements conçus avec des visuels à fort impact et une structure intuitive.',
    'pitch.feature.custom.title': 'Personnalisation Totale',
    'pitch.feature.custom.desc': 'Chaque bot que je conçois est unique. De la charte graphique à la logique spécifique, je développe des fonctionnalités adaptées à votre communauté.',
    // Sledge Example
    'pitch.example.mod.title': '[ALERTE] Détection Anti-Scam',
    'pitch.example.mod.desc': 'Un message suspect a été détecté et supprimé.',
    'pitch.example.mod.field.overview': 'Aperçu de la modération',
    'pitch.example.mod.field.user': 'Utilisateur',
    'pitch.example.mod.field.channel': 'Salon',
    'pitch.example.mod.field.incident': 'Incident',
    'pitch.example.mod.btn.ban': 'Bannir',
    'pitch.example.mod.btn.history': 'Historique',
    'pitch.example.mod.btn.dismiss': 'Ignorer',
    'pitch.example.mod.btn.evidence': 'Preuves',
    'pitch.example.notif.msg': '📹 Melias vient de lancer un live sur Twitch !\nhttps://twitch.tv/meliasoficial\n@Mention - Directs',
    'pitch.example.notif.embed.title': 'Twitch',
    'pitch.example.notif.embed.desc': 'meliasoficial - Twitch',
    // Normativas Example
    'pitch.example.rules.desc': '🔨 **Le respect des règles est obligatoire.**\n\nCe serveur est régi par les **Conditions d\'utilisation** et les **Charte de la communauté** de Discord.\n\n`Les règles sont obligatoires pour garantir un séjour paisible et respectueux. L\'ignorance des règles n\'est pas une excuse.`',
    'pitch.example.rules.f1': '🔴 Comportement',
    'pitch.example.rules.f1.v': 'Traitez les utilisateurs avec respect. Aucune discrimination ni harcèlement n\'est toléré.',
    'pitch.example.rules.f2': '🔴 Utilisation des salons textuels',
    'pitch.example.rules.f2.v': 'Évitez les messages répétitifs, le spam ou la publicité.',
    'pitch.example.rules.f3': '🔴 Contenu approprié',
    'pitch.example.rules.f3.v': 'Les contenus NSFW ou similaires ne sont pas autorisés.',
    'pitch.example.rules.f4': '🔴 Utilisation des salons',
    'pitch.example.rules.f4.v': 'Utilisez chaque salon pour l\'usage auquel il est destiné.',
    'pitch.example.rules.f5': '🔴 Confidentialité',
    'pitch.example.rules.f5.v': 'Ne partagez aucune coordonnée ou information personnelle.',
    'pitch.example.rules.f6': '🔴 Modération',
    'pitch.example.rules.f6.v': 'Ne contestez pas les décisions du personnel.',
    'pitch.example.rules.footer': 'En cas de doute, consultez les informations du serveur ou contactez l\'équipe.',
    'pitch.example.rules.btn1': 'Lire les règles',
    'pitch.example.rules.btn2': 'Voir les infos',
    // Customization Examples
    'pitch.example.custom.bio1': 'Le bot le plus complet pour la communauté de Melias. Développé par Nynele Studio.',
    'pitch.example.custom.bio2': 'Sécurité avancée et modération tactique pour serveurs professionnels.',
    'pitch.example.custom.status': '🛡️ Protection de votre serveur en cours',
    // Audio Player Widget
    'audio.select_track': 'Sélectionner une piste',
    'audio.playing_lofi': 'Lecture Lo-Fi',
    'audio.lofi_background': 'Ambiance Lo-Fi',
    'audio.live_sync_menu': 'Menu Sincro Live',
    'audio.force_refresh': 'Forcer la synchronisation',
    'audio.force_refresh_desc': 'Récupérer l\'activité Discord',
    'audio.reset_search': 'Réinitialiser la recherche',
    'audio.reset_search_desc': 'Revenir au premier résultat vidéo',
    // Discord Profile / Message
    'discord.about_me': 'À propos de moi',
    // Bot Builder
    'builder.default.name': 'Mon Bot Personnalisé',
    'builder.default.bio': 'Je suis un bot Discord professionnel adapté aux besoins de votre communauté.',
    'builder.default.tag1': 'Personnalisé',
    'builder.default.tag2': 'Sécurité',
    'builder.default.tag3': 'Rapide',
    'builder.app_icon': 'Icône de l\'app',
    'builder.remove': 'Supprimer',
    'builder.name': 'Nom',
    'builder.description_label': 'Description (Maximum 400 caractères)',
    'builder.description_help': 'Votre description apparaîtra dans la section À propos de moi du profil de votre bot.',
    'builder.tags_label': 'Tags (Maximum 5)',
    'builder.tags_placeholder': 'Ajouter jusqu\'à 5 tags...',
    'builder.preview_title': 'Aperçu du Profil en Direct',
    'builder.preview_help': 'Voici comment votre marque personnalisée apparaîtra sur Discord.',
    'builder.custom_status': '🛡️ Système de Bot Personnalisé',
    // Showcase
    'pitch.trusted_by': 'ILS ME FONT CONFIANCE',
  },
  de: {
    'hero.title': 'Discord Designer & Community Manager.',
    'hero.subtitle': 'Nachgewiesene Expertise im Entwurf und der Skalierung hochleistungsfähiger Serverinfrastrukturen. Erweiterte Berechtigungen und maßgeschneiderte Bot-Entwicklung.',
    'section.projects': 'Ausgewählte Projekte',
    'nav.home': 'Startseite',
    'nav.showcase': 'Showcase',
    'section.experience': 'Berufserfahrung',
    'cta.title': 'Lass uns zusammenarbeiten.',
    'cta.subtitle': 'Ich stehe derzeit für freiberufliche Projekte zur Verfügung. Wenn Sie ein Projekt starten möchten, Hilfe benötigen oder einfach nur Hallo sagen wollen, melden Sie sich.',
    'cta.button': 'Schreiben Sie mir',
    'discord.listening': 'Hört gerade',
    'discord.playing': 'Spielt gerade',
    'discord.activity': 'Aktivität',
    'discord.chilling': 'Chillt gerade...',
    'discord.message': 'Discord-Nachricht senden',
    'footer.copy': 'Nynele.',
    'time.local': 'LOKALE ZEIT',
    'audio.play': 'Abspielen',
    'audio.pause': 'Pause',
    'job.present': 'Heute',
    'experience.active': 'Aktuelle Positionen',
    'experience.past': 'Bisherige Positionen',
    '404.title': 'Seite nicht gefunden',
    '404.subtitle': 'Die gesuchte Seite existiert nicht oder wurde verschoben. Keine Sorge, selbst die besten Designer verlieren mal den Weg.',
    '404.button': 'Zurück zur Startseite',
    'pitch.hero.title': 'Discord Designer & Community Manager.',
    'pitch.hero.subtitle': 'Nachgewiesene Expertise im Entwurf und der Skalierung hochleistungsfähiger Serverinfrastrukturen. Erweiterte Berechtigungen und maßgeschneiderte Bot-Entwicklung.',
    'pitch.why.title': 'Warum mich engagieren?',
    'pitch.why.1': 'Experten-Konfiguration',
    'pitch.why.1.desc': 'Erweiterte Berechtigungen und Hierarchie-Setup.',
    'pitch.why.2': 'Maßgeschneiderte Automatisierung',
    'pitch.why.2.desc': 'Individuelle Bot-Lösungen für Ihre spezifischen Bedürfnisse.',
    'pitch.why.3': 'Community-Wachstum',
    'pitch.why.3.desc': 'Bewährte Strategien zur Steigerung von Engagement und Bindung.',
    'pitch.cta': 'Bereit zu wachsen?',
    'pitch.results.title': 'Die Ergebnisse',
    'pitch.results.subtitle': 'Ich baue nicht nur Server; ich baue Ökosysteme. So sieht meine Architektur unter der Haube aus.',
    'pitch.final.title': 'Lass uns etwas Großartiges aufbauen.',
    'pitch.final.subtitle': 'Verfügbar für neue Partnerschaften und Beratungen.',
    'pitch.final.button': 'Über Discord starten',
    'pitch.example.bot.name': 'Community-Hub',
    'pitch.example.bot.msg': 'Umfrage erstellt von Nynele 🤫',
    'pitch.example.bot.embed.title': 'Frage',
    'pitch.example.bot.embed.desc': 'Gefällt dir dieses neue Dashboard? 💕',
    'pitch.example.bot.embed.field1': 'Auswahl',
    'pitch.example.bot.embed.field1.val': 'A: Ja | B: Definitiv | C: Absolut!!!',
    'pitch.example.bot.embed.field2': 'Endet',
    'pitch.example.bot.embed.field2.val': 'In 1 Tag',
    'pitch.stats.servers': 'Optimierte Server',
    'pitch.stats.members': 'Verwaltete Mitglieder',
    'pitch.stats.experience': 'Jahre Erfahrung',
    'pitch.commands.title': 'Interaktive Befehle',
    'pitch.commands.hire.desc': 'Öffnen Sie ein Ticket, um Ihr Projekt zu besprechen.',
    'pitch.commands.info.desc': 'Sehen Sie sich meine Dienstleistungen und Preise an.',
    'pitch.commands.portfolio.desc': 'Durchsuchen Sie meine neuesten Discord-Setups.',
    'pitch.feature.mod.title': 'Erweiterte Moderation',
    'pitch.feature.mod.desc': 'Schützen Sie Ihre Community mit Multi-User-Bann, Kicks und erweiterten Protokollen. Automatisieren Sie den Schutz vor Raids und Spam im Handumdrehen.',
    'pitch.feature.notifications.title': 'Echtzeit-Benachrichtigungen',
    'pitch.feature.notifications.desc': 'Halten Sie Ihre Nutzer mit automatischen YouTube-, Twitch- und Social-Media-Benachrichtigungen direkt in Ihren Kanälen auf dem Laufenden.',
    'pitch.feature.embeds.title': 'Wunderschöne Embeds',
    'pitch.feature.embeds.desc': 'Professionelle Dokumentation und Regelwerke mit ansprechenden Visualisierungen und intuitiver Struktur.',
    'pitch.feature.custom.title': 'Vollständige Anpassung',
    'pitch.feature.custom.desc': 'Jeder Bot, den ich entwerfe, ist einzigartig. Vom Branding bis hin zu spezifischer Logik entwickle ich Funktionen, die perfekt zu Ihrer Community passen.',
    // Sledge Example
    'pitch.example.mod.title': '[WARNUNG] Anti-Scam-Erkennung',
    'pitch.example.mod.desc': 'Eine verdächtige Nachricht wurde erkannt und entfernt.',
    'pitch.example.mod.field.overview': 'Moderationsübersicht',
    'pitch.example.mod.field.user': 'Benutzer',
    'pitch.example.mod.field.channel': 'Kanal',
    'pitch.example.mod.field.incident': 'Vorfall',
    'pitch.example.mod.btn.ban': 'Bannen',
    'pitch.example.mod.btn.history': 'Verlauf',
    'pitch.example.mod.btn.dismiss': 'Verwerfen',
    'pitch.example.mod.btn.evidence': 'Beweise',
    'pitch.example.notif.msg': '📹 Melias hat gerade einen Live-Stream auf Twitch gestartet!\nhttps://twitch.tv/meliasoficial\n@Mention - Streams',
    'pitch.example.notif.embed.title': 'Twitch',
    'pitch.example.notif.embed.desc': 'meliasoficial - Twitch',
    // Normativas Example
    'pitch.example.rules.desc': '🔨 **Die Einhaltung der Regeln ist obligatorische.**\n\nDieser Server unterliegt den **Nutzungsbedingungen** und **Community-Richtlinien** von Discord.\n\n`Die Regeln sind zwingend erforderlich, um einen friedlichen und respektvollen Aufenthalt zu gewährleisten. Unkenntnis schützt nicht vor Strafe.`',
    'pitch.example.rules.f1': '🔴 Verhalten',
    'pitch.example.rules.f1.v': 'Behandeln Sie Benutzer mit Respekt. Diskriminierung oder Belästigung ist nicht gestattet.',
    'pitch.example.rules.f2': '🔴 Chat-Nutzung',
    'pitch.example.rules.f2.v': 'Vermeiden Sie repetitive Nachrichten, Kettenbriefe oder Werbung.',
    'pitch.example.rules.f3': '🔴 Angemessene Inhalte',
    'pitch.example.rules.f3.v': 'NSFW- oder ähnliche Inhalte sind nicht gestattet.',
    'pitch.example.rules.f4': '🔴 Kanalnutzung',
    'pitch.example.rules.f4.v': 'Nutzen Sie jeden Kanal für seinen vorgesehenen Zweck.',
    'pitch.example.rules.f5': '🔴 Privatsphäre',
    'pitch.example.rules.f5.v': 'Teilen Sie keine persönlichen Informationen jeglicher Art.',
    'pitch.example.rules.f6': '🔴 Moderation',
    'pitch.example.rules.f6.v': 'Stellen Sie Entscheidungen des Teams nicht infrage.',
    'pitch.example.rules.footer': 'Bei Fragen besuchen Sie die Server-Info oder kontaktieren Sie das Team.',
    'pitch.example.rules.btn1': 'Regeln lesen',
    'pitch.example.rules.btn2': 'Info anzeigen',
    // Customization Examples
    'pitch.example.custom.bio1': 'Der umfassendste Bot für die Community von Melias. Entwickelt von Nynele Studio.',
    'pitch.example.custom.bio2': 'Erweiterte Sicherheit und taktische Moderation für professionelle Server.',
    'pitch.example.custom.status': '🛡️ Schütze deinen Server',
    // Audio Player Widget
    'audio.select_track': 'Titel auswählen',
    'audio.playing_lofi': 'Lo-Fi wird abgespielt',
    'audio.lofi_background': 'Lo-Fi-Hintergrund',
    'audio.live_sync_menu': 'Live-Sync-Menü',
    'audio.force_refresh': 'Sync erzwingen',
    'audio.force_refresh_desc': 'Discord-Aktivität erneut abfragen',
    'audio.reset_search': 'Videosuche zurücksetzen',
    'audio.reset_search_desc': 'Zum ersten Suchergebnis zurückkehren',
    // Discord Profile / Message
    'discord.about_me': 'Über mich',
    // Bot Builder
    'builder.default.name': 'Mein Custom-Bot',
    'builder.default.bio': 'Ich bin ein professioneller Discord-Bot, angepasst an die Bedürfnisse deiner Community.',
    'builder.default.tag1': 'Custom',
    'builder.default.tag2': 'Sicherheit',
    'builder.default.tag3': 'Schnell',
    'builder.app_icon': 'App-Symbol',
    'builder.remove': 'Entfernen',
    'builder.name': 'Name',
    'builder.description_label': 'Beschreibung (Maximal 400 Zeichen)',
    'builder.description_help': 'Deine Beschreibung wird im Bereich "Über mich" des Bot-Profils angezeigt.',
    'builder.tags_label': 'Tags (Maximal 5)',
    'builder.tags_placeholder': 'Bis zu 5 Tags hinzufügen...',
    'builder.preview_title': 'Live-Profilvorschau',
    'builder.preview_help': 'So wird dein maßgeschneiderter Bot auf Discord aussehen.',
    'builder.custom_status': '🛡️ Custom-Bot-System',
    // Showcase
    'pitch.trusted_by': 'VERTRETEN DURCH',
  },
  pt: {
    'hero.title': 'Designer de Discord & Community Manager.',
    'hero.subtitle': 'Experiência comprovada em design e dimensionamento de infraestrutura de servidor de alto desempenho. Permissões avançadas e desenvolvimento de bots personalizados.',
    'section.projects': 'Projetos Selecionados',
    'nav.home': 'Início',
    'nav.showcase': 'Showcase',
    'section.experience': 'Experiência Profissional',
    'cta.title': 'Vamos trabalhar juntos.',
    'cta.subtitle': 'Atualmente estou disponível para trabalhos freelancers. Se você tem um projeto que deseja iniciar, acha que precisa da minha ajuda ou apenas quer dar um alô, entre em contato.',
    'cta.button': 'Envie-me um e-mail',
    'discord.listening': 'Ouvindo',
    'discord.playing': 'Jogando',
    'discord.activity': 'Atividade',
    'discord.chilling': 'Apenas relaxando...',
    'discord.message': 'Enviar mensagem no Discord',
    'footer.copy': 'Nynele.',
    'time.local': 'HORA LOCAL',
    'audio.play': 'Reproduzir',
    'audio.pause': 'Pausar',
    'job.present': 'Presente',
    'experience.active': 'Cargos Ativos',
    'experience.past': 'Cargos Anteriores',
    '404.title': 'Página não encontrada',
    '404.subtitle': 'A página que procura não existe ou foi movida. Não se preocupe, até os melhores designers se perdem às vezes.',
    '404.button': 'Voltar ao Início',
    'pitch.hero.title': 'Designer de Discord & Community Manager.',
    'pitch.hero.subtitle': 'Experiência comprovada em design e dimensionamento de infraestrutura de servidor de alto desempenho. Permissões avançadas e desenvolvimento de bots personalizados.',
    'pitch.why.title': 'Por que me contratar?',
    'pitch.why.1': 'Configuração Especializada',
    'pitch.why.1.desc': 'Configuração avançada de permissões e hierarquias.',
    'pitch.why.2': 'Automação Personalizada',
    'pitch.why.2.desc': 'Soluções de bots sob medida para as suas necessidades específicas.',
    'pitch.why.3': 'Crescimento de Comunidade',
    'pitch.why.3.desc': 'Estratégias comprovadas para aumentar o engajamento e a retenção.',
    'pitch.cta': 'Pronto para crescer?',
    'pitch.results.title': 'Os Resultados',
    'pitch.results.subtitle': 'Eu não crio apenas servidores; eu crio ecossistemas. Veja como é minha arquitetura por baixo do capô.',
    'pitch.final.title': 'Vamos construir algo grande.',
    'pitch.final.subtitle': 'Disponível para novas parcerias e consultorias.',
    'pitch.final.button': 'Começar via Discord',
    'pitch.example.bot.name': 'Centro da Comunidade',
    'pitch.example.bot.msg': 'Enquete criada por Nynele 🤫',
    'pitch.example.bot.embed.title': 'Pergunta',
    'pitch.example.bot.embed.desc': 'Você gostou deste novo painel? 💕',
    'pitch.example.bot.embed.field1': 'Opções',
    'pitch.example.bot.embed.field1.val': 'A: Sim | B: Com certeza | C: Com toda certeza!!!',
    'pitch.example.bot.embed.field2': 'Termina',
    'pitch.example.bot.embed.field2.val': 'Em 1 dia',
    'pitch.stats.servers': 'Servidores Otimizados',
    'pitch.stats.members': 'Membros Gerenciados',
    'pitch.stats.experience': 'Anras de Experiência', // Typo corrected: Anos de Experiência
    'pitch.commands.title': 'Comandos Interativos',
    'pitch.commands.hire.desc': 'Abra um tíquete para discutir seu projeto.',
    'pitch.commands.info.desc': 'Ver meus serviços e preços.',
    'pitch.commands.portfolio.desc': 'Explore minhas configurações mais recentes do Discord.',
    'pitch.feature.mod.title': 'Moderação Avançada',
    'pitch.feature.mod.desc': 'Mantenha sua comunidade segura com banimentos de múltiplos usuários, expulsões e registros avançados. Automatize a proteção contra ataques e spam sem esforço.',
    'pitch.feature.notifications.title': 'Notificas em Tempo Real', // Notificações
    'pitch.feature.notifications.desc': 'Mantenha seus usuários informados com alertas automáticos do YouTube, Twitch e redes sociais diretamente nos seus canais.',
    'pitch.feature.embeds.title': 'Embeds Lindos',
    'pitch.feature.embeds.desc': 'Documentação profissional e regras criadas com visuais impactantes e estrutura intuitiva.',
    'pitch.feature.custom.title': 'Personalização Total',
    'pitch.feature.custom.desc': 'Cada bot que eu crio é único. Do branding à lógica específica, crio recursos que se adaptam à sua comunidade perfeitamente.',
    // Sledge Example
    'pitch.example.mod.title': '[ALERTA] Detecção Anti-Scam',
    'pitch.example.mod.desc': 'Uma mensagem suspeita foi detectada e removida.',
    'pitch.example.mod.field.overview': 'Visão Geral da Moderação',
    'pitch.example.mod.field.user': 'Usuário',
    'pitch.example.mod.field.channel': 'Canal',
    'pitch.example.mod.field.incident': 'Incidente',
    'pitch.example.mod.btn.ban': 'Banir',
    'pitch.example.mod.btn.history': 'Histórico',
    'pitch.example.mod.btn.dismiss': 'Ignorar',
    'pitch.example.mod.btn.evidence': 'Provas',
    'pitch.example.notif.msg': '📹 Melias acabou de iniciar uma transmissão ao vivo na Twitch!\nhttps://twitch.tv/meliasoficial\n@Mencionados - Transmissões',
    'pitch.example.notif.embed.title': 'Twitch',
    'pitch.example.notif.embed.desc': 'meliasoficial - Twitch',
    // Normativas Example
    'pitch.example.rules.desc': '🔨 **O cumprimento das regras é obrigatório.**\n\nEste servidor é regido pelos **Termos de Serviço** e pelas **Diretrizes da Comunidade** do Discord.\n\n`As regras são obrigatórias para garantir uma estadia pacífica e respeitosa. A ignorância delas não o isenta do seu cumprimento.`',
    'pitch.example.rules.f1': '🔴 Comportamento',
    'pitch.example.rules.f1.v': 'Trate os usuários com respeito. Não é permitida discriminação ou assédio.',
    'pitch.example.rules.f2': '🔴 Uso de chat',
    'pitch.example.rules.f2.v': 'Evite mensagens repetitivas, correntes ou promoções.',
    'pitch.example.rules.f3': '🔴 Conteúdo apropriado',
    'pitch.example.rules.f3.v': 'Conteúdo NSFW ou semelhante não é permitido.',
    'pitch.example.rules.f4': '🔴 Uso de canais',
    'pitch.example.rules.f4.v': 'Use cada canal para o propósito para o qual foi criado.',
    'pitch.example.rules.f5': '🔴 Privacidade',
    'pitch.example.rules.f5.v': 'Não compartilhe informações pessoais de qualquer tipo.',
    'pitch.example.rules.f6': '🔴 Moderação',
    'pitch.example.rules.f6.v': 'Não questione as decisões da equipe.',
    'pitch.example.rules.footer': 'Em caso de dúvidas, visite a info do servidor ou entre em contato com a equipe.',
    'pitch.example.rules.btn1': 'Ler regras',
    'pitch.example.rules.btn2': 'Ver info',
    // Customization Examples
    'pitch.example.custom.bio1': 'O bot mais completo para a comunidade do Melias. Desenvolvido por Nynele Studio.',
    'pitch.example.custom.bio2': 'Segurança avançada e moderação tática para servidores profissionais.',
    'pitch.example.custom.status': '🛡️ Protegendo seu servidor',
    // Audio Player Widget
    'audio.select_track': 'Selecionar Faixa',
    'audio.playing_lofi': 'Reproduzindo Lo-Fi',
    'audio.lofi_background': 'Lo-Fi de Fundo',
    'audio.live_sync_menu': 'Menu de Sincronização Live',
    'audio.force_refresh': 'Forçar Sincronização',
    'audio.force_refresh_desc': 'Buscar novamente atividade do Discord',
    'audio.reset_search': 'Redefinir Pesquisa de Vídeo',
    'audio.reset_search_desc': 'Redefinir para o primeiro resultado da pesquisa',
    // Discord Profile / Message
    'discord.about_me': 'Sobre Mim',
    // Bot Builder
    'builder.default.name': 'Meu Bot Personalizado',
    'builder.default.bio': 'Sou um bot de Discord profissional adaptado às necessidades da sua comunidade.',
    'builder.default.tag1': 'Personalizado',
    'builder.default.tag2': 'Segurança',
    'builder.default.tag3': 'Rápido',
    'builder.app_icon': 'Ícone do App',
    'builder.remove': 'Remover',
    'builder.name': 'Nome',
    'builder.description_label': 'Descrição (Máximo 400 caracteres)',
    'builder.description_help': 'Sua descrição aparecerá na seção Sobre Mim do perfil do seu bot.',
    'builder.tags_label': 'Tags (Máximo 5)',
    'builder.tags_placeholder': 'Adicionar até 5 tags...',
    'builder.preview_title': 'Visualização de Perfil Live',
    'builder.preview_help': 'É assim que sua marca personalizada aparecerá no Discord.',
    'builder.custom_status': '🛡️ Sistema de Bot Personalizado',
    // Showcase
    'pitch.trusted_by': 'COM A CONFIANZA DE',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode; initialLanguage?: Language }> = ({ children, initialLanguage }) => {
  const [language, setLanguageState] = useState<Language>(initialLanguage || 'en');

  useEffect(() => {
    if (initialLanguage) {
      setLanguageState(initialLanguage);
      localStorage.setItem('language', initialLanguage);
    } else {
      const savedLang = localStorage.getItem('language') as Language;
      if (savedLang && (savedLang === 'en' || savedLang === 'es' || savedLang === 'it' || savedLang === 'fr' || savedLang === 'de' || savedLang === 'pt')) {
        setLanguageState(savedLang);
      } else {
        const browserLang = navigator.language.split('-')[0];
        if (browserLang === 'es') {
          setLanguageState('es');
        } else if (browserLang === 'it') {
          setLanguageState('it');
        } else if (browserLang === 'fr') {
          setLanguageState('fr');
        } else if (browserLang === 'de') {
          setLanguageState('de');
        } else if (browserLang === 'pt') {
          setLanguageState('pt');
        }
      }
    }
  }, [initialLanguage]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    const fallbackT = (key: string): string => {
      return translations['en'][key] || key;
    };
    return {
      language: 'en' as const,
      setLanguage: () => {},
      t: fallbackT
    };
  }
  return context;
};
